### PR TITLE
My modernizations

### PR DESCRIPTION
**Pull request by MaddTheSane**
This contains a lot of my modernizations, including:
* Basic Dark Mode support.
* Fixing a _lot_ of memory leaks.
* Migrating to Xcode assets.
* Migrating to en.lproj from English.lproj.
* Fix some deprecation warnings.
* Accent color support.
* Added constraints to the xibs.
* And "documentation" (comments in the source code that pops up under Quick Help).

Note that this ups the deployment target to ~~10.15~~ 10.14, as well as links to my own fork of Zoom (which has a lot of modernizations as well). Also, I've moved some stuff around.

I also rebuilt the `inform6` binary as an Apple Silicon/Intel Universal 2 Binary. The other binaries should also be rebuilt to have a native Apple Silicon version.

### CODE REVIEW

**Comment by TobyLobster** [comment]
Hi MaddTheSane, this looks like it could be very useful. Would it be possible to support 10.14 as a deployment target?

**Comment by MaddTheSane** [comment]
I’ll look into it.

The biggest change needed would be on ZoomView, as I’ve been poking at that longer and have done more work on Zoom as a whole.

**Comment by MaddTheSane** [comment]
I have set the deployment target to 10.14.

**Comment by TobyLobster** [comment]
Thanks for allowing the earlier deployment target. I'm keen to look through the changes, but I'm having trouble accessing the submodule. Do you have any ideas?

% git submodule status
-24d2fb90690ce8daec798a02d371c8370abd94bc zoom
% git pull --recurse-submodules
Could not access submodule 'zoom'

My knowledge of submodules in git is slim, so I'm probably doing something wrong.

**Comment by MaddTheSane** [comment]
`git submodule update --init --recursive`

**Comment by MaddTheSane** [comment]
If needed, I can remove the submodule requirement.

**Comment by TobyLobster** [comment]
Apologies for my long absence @MaddTheSane, everything else got in the way, but I am now back looking at Inform again. I'm looking at your changes and I'm seeing an issue when trying to run stories in the Glulx format (Z-Code version 8 format is working). The story compiles ok, but the story view is just white with no interaction. There are no errors on the system log, or in the Console app.
Screenshot 2022-03-31 at 08 36 37

If you have any thoughts on this, I would be interested to know. Thanks.

**Comment by MaddTheSane** [comment]
I think I found out the issue and fixed it in my personal commit of 5fdde35df09274c358eedca470d9c8548b66d2e4. I'll backport it to this pull request ASAP.

**Comment by TobyLobster** [comment]
This now seems to be referencing new audio frameworks that I don't have. The File Inspector is saying they are Absolute Path file references:

Build target Inform of project Inform with configuration Debug
/Users/tobynelson/Code/InformApp/inform/Inform.xcodeproj: error: This Copy Files build phase contains a reference to a missing file '**Ogg.framework**'. (in target 'Inform' from project 'Inform')
/Users/tobynelson/Code/InformApp/inform/Inform.xcodeproj: error: This Copy Files build phase contains a reference to a missing file '**SFBAudioEngine.framework**'. (in target 'Inform' from project 'Inform')
/Users/tobynelson/Code/InformApp/inform/Inform.xcodeproj: error: This Copy Files build phase contains a reference to a missing file '**GlkSound.framework**'. (in target 'Inform' from project 'Inform')

**Comment by MaddTheSane** [comment]
Make sure you do a `git submodule update --init --recursive`.

**Comment by TobyLobster** [comment]
Done - but I get the same issue still.

**Comment by MaddTheSane** [comment]
Did you try closing the project/Xcode and opening it again?

**Comment by TobyLobster** [comment]
Yes - still no joy.

**Comment by MaddTheSane** [comment]
I see the problem.
Stupid absolute paths…

**Comment by TobyLobster** [comment]
:-)

**Comment by TobyLobster** [comment]
That works better, thanks.

**Comment by TobyLobster** [comment]
I want to thank you for your updates. I am working on an update to the Mac App which should be released in a couple of weeks. Your changes are in and working very well locally. Many thanks.

**Comment by TobyLobster** [comment]
You may have seen that I have submitted all changes back into the Master branch, and released a beta version of the latest App. I am working on writing build instructions for it.

In the meantime, Zarf has implemented the changes required to the Glulxe and Git interpreters for version 3.1.3 of the Glulx specification (mostly, adding the opcodes for double precision maths), and there are now new releases of these interpreters.

Glulxe 0.6.0: https://github.com/erkyrath/glulxe/releases/tag/glulxe-0.6.0
Git 1.3.7   : https://github.com/DavidKinder/Git/releases/tag/v1.3.7

It would be good to update to these if possible, then I could take these and presumably all your latest Zoom work into the macOS Inform App for the proper release?

**Comment by MaddTheSane** [comment]
I updated my personal branch [here](https://github.com/MaddTheSane/zoom/commit/092028f8f5333210fa432cc177e9ffbcf3d386bb) with these requests

**Pull request merged**
